export default [
  {
    label: 'cadmin',
    list: [
      'iconfont icon-audit',
      'iconfont icon-menu',
      'iconfont icon-dept',
      'iconfont icon-user',
      'iconfont icon-role',
      'iconfont icon-tenant',
      'iconfont icon-system',
      'iconfont icon-logger',
      'iconfont icon-dict',
      'iconfont icon-file',
      'iconfont icon-config',
      'iconfont icon-quartz',
      'iconfont icon-terminal',
      'iconfont icon-key',
      'iconfont icon-token',
      'iconfont icon-route',
      'iconfont icon-monitor',
      'iconfont icon-service-monitor',
      'iconfont icon-swagger',
      'iconfont icon-redis',
      'iconfont icon-memcached',
      'iconfont icon-transcation',
      'iconfont icon-transcation-o',
      'iconfont icon-workflow',
      'iconfont icon-flow-model',
      'iconfont icon-process',
      'iconfont icon-todolist',
      'iconfont icon-develop',
      'iconfont icon-datasource',
      'iconfont icon-datamodel',
      'iconfont icon-codegen',
      'iconfont icon-design',
      'iconfont icon-form',
      'iconfont icon-sys',
      'iconfont icon-cms',
      'iconfont icon-cms-o',
      'iconfont icon-fullscreen',
      'iconfont icon-fullscreen-exit',
      'iconfont icon-refresh',
      'iconfont icon-navicon',
      'iconfont icon-remind',
      'iconfont icon-lock',
      'iconfont icon-theme',
      'iconfont icon-book',
      'iconfont icon-data-model',
      'iconfont icon-todo-list',
      'iconfont icon-done-list'
    ]
  }
]
